---

- name: Practice secrets
  hosts: ubu
  gather_facts: false

  tasks:
    - name: Load a secrets file
      ansible.builtin.include_vars:
        file: secrets.yml

    - name: Debug a secret
      ansible.builtin.debug:
        var: name

    - name: Debug with no_log
      ansible.builtin.debug:
        var: name
      no_log: true

